spring.application.name=group-manage-service
# server.port=8081
server.port=${PORT:8280}

spring.datasource.url=jdbc:mysql://localhost:3306/group_manage_service?createDatabaseIfNotExist=true&encoding=UTF-8
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379



reladomo.database.url=localhost
reladomo.database.port=3306
reladomo.database.username=root
reladomo.database.password=yourpassword
reladomo.database.driver=com.mysql.cj.jdbc.Driver
reladomo.database.schema=group_manage_service
